# Generated by Django 5.2.7 on 2025-11-08 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('raw_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConversationAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clarity_score', models.FloatField()),
                ('relevance_score', models.FloatField()),
                ('accuracy_score', models.FloatField()),
                ('completeness_score', models.FloatField()),
                ('empathy_score', models.FloatField()),
                ('sentiment', models.CharField(max_length=20)),
                ('fallback_count', models.IntegerField()),
                ('resolution', models.BooleanField()),
                ('resolution_rate', models.FloatField()),
                ('avg_response_time', models.FloatField(blank=True, null=True)),
                ('escalation_need', models.BooleanField()),
                ('overall_score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='analysis.conversation')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=20)),
                ('text', models.TextField()),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='analysis.conversation')),
            ],
        ),
    ]
