# Generated by Django 5.2.7 on 2025-11-08 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationanalysis',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
